config/routes.rb
Rails.application.routes.draw do

  
  resources :campaign_pages
  resources :waitlists


  # get 'sponsors/index'

  # get 'sponsors/show'

  # get 'sponsors/new'

  # get 'sponsors/edit'

  resources :sponsors

  # devise_for :users
  
  root to: "pages#welcome"
  
  # get 'proposals/Index'

  # get 'proposals/Show'

  # get 'proposals/Edit'

  # get 'proposals/New'

# namespace :org do
#     root "org", to: "org#show"
# end


  # get 'event_pages/index'

  # get 'event_pages/show'

  # get 'event_pages/edit'

  # get 'event_pages/update'




  namespace :admin do
    resources :orgs
    resources :businesses
    resources :events
    resources :users
    resources :event_pages
    
    root to: "orgs#index"
  end

  # get 'events/index'

  # get 'events/show'

  # get 'events/edit'

  # resources :events

  # get 'orgs/index'

  get 'orgs/show'

  # devise_for :orgs
  # devise_for :businesses


  devise_for :businesses, path: 'businesses',  controllers: {
        sessions: 'businesses/sessions',
        registrations: "businesses/registrations",
        confirmations: "businesses/confirmations",
        passwords: "businesses/passwords",
        unlocks: "businesses/unlocks",

      }

  devise_for :orgs, path: 'orgs', controllers: {
        sessions: 'orgs/sessions',
        registrations: "orgs/registrations",
        confirmations: "orgs/confirmations",
        passwords: "orgs/passwords",
        unlocks: "orgs/unlocks",

      }


 devise_for  :users, path: 'users', controllers: {
        sessions: 'users/sessions',
        registrations: "users/registrations",
        confirmations: "users/confirmations",
        passwords: "users/passwords",
        unlocks: "users/unlocks",

  }




 resources :businesses
 resources :orgs
 resources :users
  

  get 'pages/welcome'

  get 'pages/about'

  get 'pages/home'
  
  get 'pages/ourcause'


  resources :businesses do
    resources :events
  end

  resources :orgs do
    resources :events
    resources :proposals
  end

  resources :events do
    member do
      patch :confirmation
      put :confirmation
    end
  end

resources :event_pages



resources :proposals do
  resources :bids
end







  # get 'businesses/index'

  # get 'businesses/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/businesses_controller.rb
module Admin
  class BusinessesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Business.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Business.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/businesses/confirmations_controller.rb
# frozen_string_literal: true

class Businesses::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/businesses/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Businesses::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/businesses/passwords_controller.rb
# frozen_string_literal: true

class Businesses::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/businesses/registrations_controller.rb
# frozen_string_literal: true

class Businesses::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
     super
     if @business.persisted?
      BusinessNotifierMailer.send_signup_email(@business).deliver
      
    end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/businesses/sessions_controller.rb
# frozen_string_literal: true

class Businesses::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  

  
  # skip_before_action :verify_signed_out_user

  # after_action :after_sign_out_path_for, only: :destroy

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

   # DELETE /resource/sign_out
    def destroy
      signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    
      redirect_to root_path
      

      set_flash_message! :notice, :signed_out if signed_out

      yield if block_given?
      root_path
   end

   

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

private 

   # Overwriting the sign_out redirect path method
  

  



  def verify_signed_out_user
    if all_signed_out?
      set_flash_message! :notice, :already_signed_out

      respond_to_on_destroy
    end
  end
end

app/controllers/businesses/unlocks_controller.rb
# frozen_string_literal: true

class Businesses::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.paginate(:page => params[:page], per_page: 7)
  end


  def show
    @business = Business.friendly.find(params[:id])
    @events = @business.events
    @event = Event.new
  end



private

 def bus_params
   params.require(:business).permit(:name,
                                    :email,
                                    :phone,
                                    :manager,
                                    :bus_type,
                                    :address_1,
                                    :address_2,
                                    :city,
                                    :region,
                                    :zip_code,
                                    :page,
                                    :main_image,
                                    :thumb_image
                                  )
 end



end

app/helpers/businesses_helper.rb
module BusinessesHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img f
    if f.business_image?
      f.business_image
    else
      image_generator(height: '200', width: '150')
    end
  end
end

app/views/businesses/index.html.erb
<body class="animsition">
    <div class="wrapper">
        <div class="search-content blog-content">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="side-widget space30">
                            <h5>Filter Listings</h5>
                            <div class="side-cat2">
                                <form>
                                    <select class="categorie">
                                        <option>Categories</option>
                                        <option>Restaurants</option>
                                        <option>Caffe</option>
                                        <option>Sport</option>
                                    </select>
                                    <input class="keyword" type="search" placeholder="Keyword">
                                    <input class="location" type="search" placeholder="Location">
                                    <input class="radius" type="search" placeholder="Radius (5 km)">
                                    <input class="reviews" type="search" placeholder="Reviews count (2)" disabled>
                                    <input type="checkbox" class="cbox" name="r-cbox" id="r-cbox1" />
                                    <label for="r-cbox1"> <span class="star-ratings">
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                </span> </label>
                                    <br/>
                                    <input type="checkbox" class="cbox" name="r-cbox" id="r-cbox2" />
                                    <label for="r-cbox2"> <span class="star-ratings">
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o no"></i>
                                </span> </label>
                                    <br/>
                                    <input type="checkbox" class="cbox" name="r-cbox" id="r-cbox3" />
                                    <label for="r-cbox3"> <span class="star-ratings">
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o"></i>
                                <i class="fa fa-star-o no"></i>
                                <i class="fa fa-star-o no"></i>
                                </span> </label>
                                    <br/>
                                    <button type="submit">Search listings</button>
                                </form>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-9 dir-search dir-search-list">
                            <div class="row">
                                <div class="col-md-10">
                                    <% @businesses.each do |f| %>
                                        <div class="listing space30">
                                            <div class="listing-info row">
                                                <div class="col-md-4">
                                                    <div class="">
                                                        <%= image_tag portfolio_img(f), width: '100%' %>
                                                    </div>
                                                </div>
                                                <div class="col-md-8">
                                                    <h4 class="li-name"><%= link_to f.name, business_path(f) %>  </h4>
                                                    <p class="li-category">Caffe,restaurant</p>
                                                    <p class="li-location"> <%= f.address_1 %> </p>
                                                    <p> <%#= link_to "Book", new_org_event_path(current_org.id) , class:'btn btn-primary' %></p>
                                                    <% if current_business and current_business.id == f.id %>
                                                            <p> <%= link_to "edit", edit_business_registration_path %></p>
                                                    <% end %>
                                                </div>
                                            </div>
                                        </div>
                                    <% end %>
                               </div>
                            </div>
                            <!-- <div><%= will_paginate @businesses %></div> -->
                            <div><%= will_paginate @businesses, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/businesses/show.html.erb
<div class="main-container">
  <div class="headerpic">
  </div>
    <div class="logopic rounded">
    </div>
    <section class="space-sm">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-12 col-md-8 col-lg-7 mt--8">
                    <div>
                        <h1> <%= @business.name %> </h1>
                        <h2 class="lead mb-3">Modern coffee house with </h2>
                        <div class="d-flex align-items-center">
                            <span class="badge badge-secondary mr-3">Restaurant</span>
                            <ul class="list-inline text-small d-inline-block">
                                <li class="list-inline-item"><i class="icon-thumbs-up"></i> Rating</li>
                                <li class="list-inline-item"><i class="icon-message"></i> 6</li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                    <h5 class="mb-4">Overview</h5>
                    <article>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut <a href="#">labore et dolore</a> magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                            ex ea commodo consequat.
                        </p>
                        <ul>
                            <li>
                                Temporibus autem quibusdam
                            </li>
                            <li>
                                Saepe eveniet ut et voluptates repudiandae sint
                            </li>
                            <li>
                                Nemo enim ipsam voluptatem quia voluptas
                            </li>
                            <li>
                                Atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.
                            </li>
                        </ul>
                    </article>
                    <hr>
                    <h5 class="mb-4">Previoous Customers</h5>
                </div>

                <!--end of col-->
                <div class="col-12 col-md-4">
                    <div class="card mar-b">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6052.255779374734!2d-73.9634766!3d40.671151!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25b0a45bce6bb%3A0x5bf020f45a685ee6!2s200+Eastern+Pkwy%2C+Brooklyn%2C+NY+11238%2C+USA!5e0!3m2!1sen!2sau!4v1512181921736"
                        allowfullscreen class="card-img-top w-100"></iframe>
                        <div class="card-body">
                            <h5> <%= @business.name %> </h5>
                            <p>
                                200 Eastern Pkwy
                                <br>Brooklyn, NY 11238 USA
                            </p>
                            <div>
                                <a href="#" class="btn btn-outline-primary">Directions</a>
                            </div>
                        </div>
                    </div>

                    <div class="card">
                        <div class="card-body">
                            <p class="lead">Set up a Funraise?</p>
                            <% if current_business != @business  %>
                                <div class="dp-contact">
                                    <h5>Request Event!</h5>
                                    <p>we usually respond within 3 hours</p>
                                    <%= form_for [ @business, @event] do |f| %>
                                        <%= f.text_field :name, placeholder: 'Name'   %>
                                        <%= f.text_field :about, placeholder: "Tell me about your event!" %>
                                        <%#= f.text_field :number_of_guess, placeholder: "Minimum Number of Guess" %>
                                        <%= f.button :submit, class:"btn btn-outline-primary" %>
                                    <% end %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                    <br>

                    <div class="card card-borderless add-card mar-b ">
                        <a class="card-body" href="#">
                            <div class="d-flex justify-content-between mb-3">
                                <img alt="Image" src="assets/img/logo-w-gradient.svg" />
                                <span class="title-decorative">Sponsor</span>
                            </div>
                            <span class="h6">A robust suite of styled elements and pages for Bootstrap 4</span>
                        </a>
                    </div>
                    <!-- end card -->
                  <!--   <div class="card mar-b">
                        <div class="card-header d-flex justify-content-between">
                            <div>
                                <span class="h6">Recent photos</span>
                            </div>
                            <a href="#">View all &rsaquo;</a>
                        </div>
                        <div class="card-body">
                            <div class="image-gallery">
                                <img alt="Image" src="assets/img/photo-man-laptop.jpg" data-action="zoom" data-width="800" data-height="600" />
                                <img alt="Image" src="assets/img/photo-man-meeting.jpg" data-action="zoom" />
                                <img alt="Image" src="assets/img/photo-woman-cafe.jpg" data-action="zoom" />
                            </div>
                        </div>
                    </div> -->
                    <!--end of card-->
                   
                    <!-- end card -->
                   
                    <!-- end card -->
                </div>
                <!--end of col-->
            </div>
            <!--end of row-->
        </div>
        <!--end of container-->
    </section>
    <!--end of section-->

</div>

app/views/businesses/show1.html.erb
<% provide(:title, @event.title) %> 

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <!-- Event Content -->
        <h1 class="center" class="wrap"><%= @page.event_name %></h1>

        <h5 class="center">Category: N/a</h5>
        <hr>
        <p class="lead center">Created by: <%= link_to @event.user.name, @event.user %></p>
        <!-- add invited by: next -->
        <p class="lead center"><b>Time:</b> tba<%#= @event.date.strftime("%I : %M %p") %><br><i class="fa fa-calendar"></i><b> Event Date: </b><%= @page.date_start.strftime("%F") %></p>

        <%# if @event.picture? %>
          <%#= image_tag @event.picture.url, class: "img-responsive", id: "event-show-image", alt: @event.picture %>
        <%# else %>
          <%#= image_tag "event-show-default.jpg", class: "img-responsive", alt: "default-image" %>
        <%# end %><br>

        <p class="lead wrap">Event Description: <%= @page.about %></p><br>
        <% if current_org %>
            <%#= social_share_button_tag(@page.event_name) %>
            <p class="lead center" ><%= link_to "Edit Event", event_pages_edit_path(@page), class: "btn btn-primary", id: "show-edit-button" %><%= link_to "Delete Event", @event, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-primary" %></p>
        <% elsif @event.date > Time.now  %>
          <div id="attend_form" >
            <%# if current_user.attending?(@event) %>
              <%#= render "unattend" %>
            <%# else %>
              <%#= render "attend" %>
            <%# end %>
          </div>
        <% else %>
          <p class="center">Event has ended</p>
        <% else %>  
          <h4 class="lead center" >(Please <%= link_to "Log In", login_path %> or  <%= link_to "Sign Up", signup_path %> to attend and comment on this event)</h4>
        <% end %><br>
 
        <!-- Attendees -->
        <% if @event.date > Time.now %> 
          <p class="lead center">People attending this event (<span id="attendees"><%#= @event.attendees.count %></span>)</p>
        <% else %>
          <p class="lead center" >People that attended this event (<span id="attendees"><%#= @event.attendees.count %></span>)</p> 
        <% end %>
        <hr>
        <div id="users_attending" >
          <%# @event.attendees.each do |user| %>
            <li style="text-align:center; list-style: none; font-size: 16px;">Name: <%#= link_to user.name, user %></li>
          <%# end %>
        </div>
        <hr id="separator">

        <!-- Comments -->
        <h3 class="center" id="comment_count">Comments (<%#= @event.comments.count %>)</h3>
        <hr>
        <div class="media comment_list" ">
          <%#= render @comments %>
        </div>
        <%# if current_user %>
          <div class="well">
            <h4>Leave a Comment:</h4>
            <%#= render 'comments/form' %>
          </div>
        <% end %>
      </div>
      <!-- Event Sidebar -->
      <div class="col-md-4">
        <!-- Map -->
        <!-- <div class="well" id="event-sidebar">
          <p class="lead"><b>Location:</b> <%= @event.address %></p>
          <div id="map"></div>
        </div> -->
      </div>
    </div>
  </div>
  <!-- <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(15);
    });
  </script> -->