config/routes.rb
Rails.application.routes.draw do

  
  resources :campaign_pages
  resources :waitlists


  # get 'sponsors/index'

  # get 'sponsors/show'

  # get 'sponsors/new'

  # get 'sponsors/edit'

  resources :sponsors

  # devise_for :users
  
  root to: "pages#welcome"
  
  # get 'proposals/Index'

  # get 'proposals/Show'

  # get 'proposals/Edit'

  # get 'proposals/New'

# namespace :org do
#     root "org", to: "org#show"
# end


  # get 'event_pages/index'

  # get 'event_pages/show'

  # get 'event_pages/edit'

  # get 'event_pages/update'




  namespace :admin do
    resources :orgs
    resources :businesses
    resources :events
    resources :users
    resources :event_pages
    
    root to: "orgs#index"
  end

  # get 'events/index'

  # get 'events/show'

  # get 'events/edit'

  # resources :events

  # get 'orgs/index'

  get 'orgs/show'

  # devise_for :orgs
  # devise_for :businesses


  devise_for :businesses, path: 'businesses',  controllers: {
        sessions: 'businesses/sessions',
        registrations: "businesses/registrations",
        confirmations: "businesses/confirmations",
        passwords: "businesses/passwords",
        unlocks: "businesses/unlocks",

      }

  devise_for :orgs, path: 'orgs', controllers: {
        sessions: 'orgs/sessions',
        registrations: "orgs/registrations",
        confirmations: "orgs/confirmations",
        passwords: "orgs/passwords",
        unlocks: "orgs/unlocks",

      }


 devise_for  :users, path: 'users', controllers: {
        sessions: 'users/sessions',
        registrations: "users/registrations",
        confirmations: "users/confirmations",
        passwords: "users/passwords",
        unlocks: "users/unlocks",

  }




 resources :businesses
 resources :orgs
 resources :users
  

  get 'pages/welcome'

  get 'pages/about'

  get 'pages/home'
  
  get 'pages/ourcause'


  resources :businesses do
    resources :events
  end

  resources :orgs do
    resources :events
    resources :proposals
  end

  resources :events do
    member do
      patch :confirmation
      put :confirmation
    end
  end

resources :event_pages



resources :proposals do
  resources :bids
end







  # get 'businesses/index'

  # get 'businesses/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :campaign_pages
    
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@user = User.all
  end

  def show
  	@user = User.find(params[:id])
    @campaings = @user.campaign_pages
  end

  

  

  def edit
  end


private


  def user_params 
		params.require(:user_params).permit(:email, :name, :admin)
  end 



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<br>
<br>
<br>
<div class="container oBody">
    <div class="row card">
        <div class="col-xs-12 col-sm-6 col-md-6 ">
            <div class="well well-sm ">
                <div class="row ">
                    <div class="col-sm-6 col-md-4 p-3">
                         <img src="http://placehold.it/180x190" alt="" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4><%#= @org.name  %></h4>
                        <p><%#= @org.manager %></p>
                        <small><cite title="San Francisco, USA">San Francisco, USA <i class="glyphicon glyphicon-map-marker">
                        </i></cite></small>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>email@example.com
                            <br />
                            <i class="glyphicon glyphicon-globe"></i><a href="http://www.jquery2dotnet.com">www.jquery2dotnet.com</a>
                            <br />
                            <i class="glyphicon glyphicon-gift"></i>June 02, 1988
                        </p>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>

<div class="container ">
    <p>Completing an event proposal will alert potential sponsors allowing them to bid for your business. Browse through the proposals and pick the sponsor that best meets your needs. 
    </p>
    <!-- 	<h5> Info:</h5>	
    	<div class="row profileTop">
    		<div class="leftDiv">
    			<p> Organization:<br> <%#= @org.name %> </p> <br>
    			<p> Manager: <br> <%#= @org.manager %> </p> <br>	
    		</div>
    	</div>
     -->
     	<br>
    <h5> Campaings :</h5>
    <% @campaings.each do |f| %>
        <div class="">
        	<div class="row eventCard ">
        		<div class="col-md-3 border-right">
        		  <p class="m-b0" >Title: <%= f.title %></p>
                  
                  <p class="m-b0"> Sponsor: <%#= link_to f.business.name, business_path(f.business)%> <%#= f.business.id %> </p>   
                  <p class="m-b0">  <%= link_to "edit",  edit_campaign_page_path(f) %> </p>   
                  <p class="m-b0">  <%= link_to "show",  campaign_page_path(f) %> </p>   
        		</div>

        		<div class="col-md-7 border-right">
        			<%#= link_to f.business.name, business_path(f.business)   %>
        		</div>

                <div class="col-md-2">
                    <%# if org_signed_in? %>
                        <%# if !f.org_active %>
                            <%#= link_to "Accept Event", confirmation_event_path( f , event: { org_active: true } ), method: :put %>
                        <%# else %>
                            <%#= link_to "Cancell Event", confirmation_event_path( f , event: { org_active: false } ), method: :put %>
                        <%#end %>
                    <%# end %>
                    <p>Contact sponsor</p>
                </div>
        	</div>
        </div>
        <br>
        <br>
    <% end %>

</div>


<%# @event_pages.each do |f| %>
 <%#= link_to f.event_name, event_page_path(f) %>  <%#= link_to "edit", edit_event_page_path(f) %> <br>
<%# end %>



<%#= link_to "Delete", room_path(room, room: {name: nil, address: nil}) , method: :put, data: { confirm: "You sure?"} %>