config/routes.rb
Rails.application.routes.draw do

  
  resources :campaign_pages
  resources :waitlists


  # get 'sponsors/index'

  # get 'sponsors/show'

  # get 'sponsors/new'

  # get 'sponsors/edit'

  resources :sponsors

  # devise_for :users
  
  root to: "pages#welcome"
  
  # get 'proposals/Index'

  # get 'proposals/Show'

  # get 'proposals/Edit'

  # get 'proposals/New'

# namespace :org do
#     root "org", to: "org#show"
# end


  # get 'event_pages/index'

  # get 'event_pages/show'

  # get 'event_pages/edit'

  # get 'event_pages/update'




  namespace :admin do
    resources :orgs
    resources :businesses
    resources :events
    resources :users
    resources :event_pages
    
    root to: "orgs#index"
  end

  # get 'events/index'

  # get 'events/show'

  # get 'events/edit'

  # resources :events

  # get 'orgs/index'

  get 'orgs/show'

  # devise_for :orgs
  # devise_for :businesses


  devise_for :businesses, path: 'businesses',  controllers: {
        sessions: 'businesses/sessions',
        registrations: "businesses/registrations",
        confirmations: "businesses/confirmations",
        passwords: "businesses/passwords",
        unlocks: "businesses/unlocks",

      }

  devise_for :orgs, path: 'orgs', controllers: {
        sessions: 'orgs/sessions',
        registrations: "orgs/registrations",
        confirmations: "orgs/confirmations",
        passwords: "orgs/passwords",
        unlocks: "orgs/unlocks",

      }


 devise_for  :users, path: 'users', controllers: {
        sessions: 'users/sessions',
        registrations: "users/registrations",
        confirmations: "users/confirmations",
        passwords: "users/passwords",
        unlocks: "users/unlocks",

  }




 resources :businesses
 resources :orgs
 resources :users
  

  get 'pages/welcome'

  get 'pages/about'

  get 'pages/home'
  
  get 'pages/ourcause'


  resources :businesses do
    resources :events
  end

  resources :orgs do
    resources :events
    resources :proposals
  end

  resources :events do
    member do
      patch :confirmation
      put :confirmation
    end
  end

resources :event_pages



resources :proposals do
  resources :bids
end







  # get 'businesses/index'

  # get 'businesses/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :business
  belongs_to :proposal
end

app/models/business.rb
class Business < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  extend FriendlyId
  friendly_id :name, use: :slugged



  mount_uploader :business_image, BusinessImageUploader


  has_many :events, dependent: :destroy
  has_many :orgs, through: :events


  


  #alias_attribute :slug, :column_name

end

app/models/campaign_page.rb
class CampaignPage < ApplicationRecord
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId

  belongs_to :org, optional: true
  belongs_to :business, optional: true
  has_one :event_page, :dependent => :destroy

   friendly_id :event_name, use: :slugged
end

app/models/event_page.rb
class EventPage < ApplicationRecord
  belongs_to :business, optional: true
  belongs_to :org, optional: true
  belongs_to :event, optional: true

  has_one :org, through: :event


  

end

app/models/org.rb
class Org < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :events, dependent: :destroy
  has_many :businesses, through: :events

  has_many :pages, dependent: :destroy

  has_one :event_pages, through: :events


end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :org
  

  has_many :bids
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :campaign_pages
    
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img f
    if f.business_image?
      f.business_image
    else
      image_generator(height: '200', width: '150')
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper

	
end

app/helpers/pages_helper.rb
module PagesHelper


end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/shared/_adds.html.erb
<!-- <div class="container">
  <%# provide(:title, @page.name) %> 
<div class="container">
	<div class="header-row" id="header-row" style="padding: 0px; overflow:hidden; height:100px;">
		<div class="container-fluid" style="padding: 0px;">
			<div class="row"> 
			    <div class="col-xs-12"> 
			        <a class="navbar-brand logo" href="index.html">
				         place your image here -->
			           <!-- <img src="http://placekitten.com/g/1200/600" alt="company logo" style="width: 100%;">
			        </a> 
			    </div>     
			</div>
		</div>
    </div>
</div> -->

app/views/shared/_admin_navbar.html.erb
<div class="container ">
  <header>
    <div class="container">
    <nav class="navbar  navbar-expand-lg navbar-light bg-light fixed-top border-bottom navbar-1 navbar-custom">
      <a class="navbar-brand" href="/">FundRaizable</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">       
          <li class="nav-item sponsor-list">
            <%= link_to "Find a Sponsor", businesses_path, class: "nav-link sponsor-list ml-5 FindSponsor rounded-pill" %>
          </li>
        </ul>
        <!-- Links leaning right use ml-auto -->
        
        <!-- LInks linig to the right  -->
        <ul class="navbar-nav ml-auto busNab2 " >
          <li class="nav-item">   
              <%= link_to "Sign Up to Fundraise", new_org_registration_path, class:'nav-link' %>   
          </li>
          <li class="nav-item">
              <%= link_to "For Vendors/Businesses", new_business_registration_path, class:'nav-link' %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto busNab login ">  
          <li class="nav-item">
             <%= link_to "About", pages_about_path, class:'nav-link' %>
          </li>
          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">login
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Admin logout ',  new_user_session_path, class: 'dropdown-item' %>
              <%#= link_to 'Fundee login ',  new_business_session_path, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    </div>
  </header>
  </div>  <div class="container ">
    <header>
      <div class="container">
      <nav class="navbar  navbar-expand-lg navbar-light bg-light fixed-top border-bottom navbar-1 navbar-custom">
        <a class="navbar-brand" href="/">FundRaizable</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">       
            <li class="nav-item sponsor-list">
              <%= link_to "Find a Sponsor", businesses_path, class: "nav-link sponsor-list ml-5 FindSponsor rounded-pill" %>
            </li>
          </ul>
          <!-- Links leaning right use ml-auto -->
          
          <!-- LInks linig to the right  -->
        <ul class="navbar-nav ml-auto busNab2 " >
          <li class="nav-item">   
              <%= link_to "Sign Up to Fundraise", new_org_registration_path, class:'nav-link' %>   
          </li>
          <li class="nav-item">
              <%= link_to "For Vendors/Businesses", new_business_registration_path, class:'nav-link' %>
          </li>

          <!-- <li class="nav-item about-b">
             <%= link_to "About", pages_about_path, class:'nav-link' %>
          </li> -->
  
        </ul>


        <ul class="navbar-nav ml-auto busNab login ">
 
          <li class="nav-item">
             <%= link_to "About", pages_about_path, class:'nav-link' %>
          </li>
          <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">login
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Vendor login ',  new_org_session_path, class: 'dropdown-item' %>
              <%= link_to 'Fundee login ',  new_business_session_path, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
        </div>
      </nav>
      </div>
    </header>
  </div>  <div class="container ">
    <header>
      <div class="container">
      <nav class="navbar  navbar-expand-lg navbar-light bg-light fixed-top border-bottom navbar-1 navbar-custom">
        <a class="navbar-brand" href="/">FundRaizable</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">       
            <li class="nav-item sponsor-list">
              <%= link_to "Find a Sponsor", businesses_path, class: "nav-link sponsor-list ml-5 FindSponsor rounded-pill" %>
            </li>
          </ul>
          <!-- Links leaning right use ml-auto -->
          
          <!-- LInks linig to the right  -->
        <ul class="navbar-nav ml-auto busNab login ">
          <li class="nav-item">
             <%= link_to "About", pages_about_path, class:'nav-link' %>
          </li>
          <li class="nav-item dropdown ">
            <a class="nav-link fas fa-user-alt" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%#= link_to "Profile", org_path(current_org), class: 'dropdown-item'  %>
              <%= link_to "logout", destroy_org_session_path(current_org), method: :delete, class: 'dropdown-item'  %>
              <%= link_to "Dashboar", admin_user_path(current_user), class: 'dropdown-item' %>
              <%= link_to "Dashboar2", user_path(current_user), class: 'dropdown-item' %>
              <%= link_to "new Campaign", new_campaign_page_path, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
        </div>
      </nav>
      </div>
    </header>
</div>

  

app/views/shared/_bus_navbar.html.erb
<div class="container ">
  <header>
    <div class="container">
    <nav class="navbar  navbar-expand-lg navbar-light bg-light fixed-top border-bottom navbar-1 navbar-custom">
      <a class="navbar-brand" href="/">FundRaizable</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto busNab login ">
          <li class="nav-item">
             <%= link_to "About", pages_about_path, class:'nav-link' %>
          </li>

          <li class="nav-item">
             <%= link_to "About", pages_about_path, class:'nav-link' %>
          </li>
          <li class="nav-item dropdown ">
            <a class="nav-link  fas fa-user-alt" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Profile',  business_path(current_business), class: 'dropdown-item' %>
              <%= link_to 'logout',  destroy_business_session_path(current_business), method: :delete , class: 'dropdown-item' %>
              <%= link_to 'Events', business_events_path(current_business), class: "dropdown-item" %>
              <%= link_to 'Edit', edit_business_registration_path(current_business), class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    </div>
  </header>
</div>

app/views/shared/_campaign_page.html.erb
<div class="container">
  <header>
    <div class="container">
    <nav class="navbar  navbar-expand-lg navbar-light bg-light fixed-top border-bottom navbar-1 navbar-custom">
      <a class="navbar-brand" href="/">FundRaizable</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto busNab login ">
          <li class="nav-item">
             <%= link_to "About", pages_about_path, class:'nav-link' %>
          </li>
          <li class="nav-item dropdown ">
            <a class="nav-link " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%#= link_to 'Profile',  business_path(current_business), class: 'dropdown-item' %>
              <%#= link_to 'logout',  destroy_business_session_path(current_business), method: :delete , class: 'dropdown-item' %>
              <%#= link_to 'Events', business_events_path(current_business), class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    </div>
  </header>
</div>

app/views/shared/_event_warning.html.erb
<% if current_business.events.last.new_record? %>
	<%= current_business %>
	<h1>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos numquam, voluptatum tempora distinctio nihil exercitationem assumenda error quaerat, non molestiae architecto est voluptates perferendis sit deserunt enim pariatur eum incidunt.
	</h1>
	<%#= current_business.campaign_pages.last.new_record? %>

<% end %>

app/views/shared/_footer.html.erb
<footer class="container blog-footer ">
    <p class="float-right"> <a href="#">Back to top</a></p>
    
    <p>&copy; 2017-2019 | FundRaisable, Inc. All rights reserved &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a> 
    	&middot; <%= link_to ' admin', new_user_session_path %>							   
    </p>
    <p class="float-left"> <a href="#">Use FundRaisable</a>  </p>

</footer > 

app/views/shared/_navbar.html.erb
   <header>
      <div class="container">
	      <nav class="navbar  navbar-expand-lg navbar-light bg-light fixed-top border-bottom navbar-1 navbar-custom">
	        <a class="navbar-brand ml-5" href="/">FundRaizable</a>
	        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	          <span class="navbar-toggler-icon"></span>
	        </button>

	        <div class="collapse navbar-collapse" id="navbarNavDropdown">
	          <ul class="navbar-nav">       
	            <li class="nav-item sponsor-list">
	              <%= link_to "Find a Sponsor", businesses_path, class: "nav-link sponsor-list ml-5 FindSponsor rounded-pill" %>
	            </li>
	          </ul>
	          <ul class="navbar-nav">       
	            <li class="nav-item sponsor-list">
	              <%#= link_to "Find a Sponsor", businesses_path, class: "nav-link sponsor-list ml-5 FindSponsor rounded-pill" %>
	            </li>
	          </ul>
	          <!-- Links leaning right use ml-auto -->
	          
	          <!-- LInks linig to the right  -->
	          <ul class="navbar-nav ml-auto busNab2 " >
	            <li class="nav-item mr-4">   
	                <%= link_to "Start a Campaign", new_org_registration_path, class:'nav-link' %>   
	            </li>
	            <li class="nav-item">
	              <%= link_to "Become a Sponsor", new_business_registration_path, class:'nav-link' %>
	            </li>
	          </ul>
	          <ul class="navbar-nav ml-auto busNab login ">
	            <li class="nav-item">
	               <%#= link_to "About", pages_about_path, class:'nav-link' %>
	            </li>
	            <li class="nav-item dropdown ">
	              <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Log in
	              </a>
	              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	                <%= link_to 'Sponsor login',  new_business_session_path, class: 'dropdown-item' %>
	                <%= link_to 'Fundraiser login',  new_org_session_path, class: 'dropdown-item' %>
	              </div>
	            </li>
	          </ul>
	        </div>

	      </nav>

      </div>
    </header>

app/views/shared/_org_navbar.html.erb
<div class="container border-bottom">
  <header>
    <div class="container">
    <nav class="navbar  navbar-expand-lg navbar-light bg-light fixed-top border-bottom navbar-1 navbar-custom">
      <a class="navbar-brand" href="/">FundRaizable</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">       
            <li class="nav-item sponsor-list">
              <%= link_to "Find a Sponsor", businesses_path, class: "nav-link sponsor-list ml-5 FindSponsor rounded-pill" %>
            </li>
          </ul>
        <ul class="navbar-nav ml-auto busNab login ">
          <li class="nav-item">
             <%= link_to "About", pages_about_path, class:'nav-link' %>
          </li>
          <li class="nav-item dropdown ">
            <a class="nav-link  fas fa-user-alt" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'Profile',  org_path(current_org), class: 'dropdown-item' %>

              <%= link_to 'logout',  destroy_org_session_path(current_org), method: :delete , class: 'dropdown-item' %>
              
              <%= link_to 'Edit', edit_org_registration_path(current_org), class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    </div>
  </header>
</div>

app/views/shared/_waitlist.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <form>
        <div class="form-group">
          <!-- <label for="exampleInputEmail1">Email address</label> -->
          <input type="email" class="form-control form-control-lg" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <!-- <label for="formGroupExampleInput">Company Name</label> -->
          <input type="text" class="form-control form-control-lg" id="formGroupExampleInput" placeholder="Company name">
        </div>

        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Sponsor</label>
        </div>
        
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
          <label class="form-check-label" for="defaultCheck1">
            Default checkbox</label>
        </div>

        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck2" disabled>
          <label class="form-check-label" for="defaultCheck2">
            Disabled checkbox
          </label>
        </div>



        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      





    </div>
  </div>
</div>

app/views/shared/_waitlist2.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog " role="document">
    <div class="modal-content ">
      <div class="modal-header d-flex justify-content-center">
        <h5 class="modal-title" id="exampleModalLabel">We are in closed beta!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body  ">
          <p>Enter your email to request an early invitation!</p>
          <%= form_for(Waitlist.new, :url => waitlists_path, :html => {:class => 'pop-sign-up'}) do |f| %>
                <div class=""> 
                  <%= f.email_field :email, type:"email" , class:"form-control form-control-lg", placeholder:"EMAIL ADDRESS" %> 
                </div>
                <%= f.submit "Submit", class:'btn btn-primary mt-1 ' %> 
          <% end %>
      </div>
  </div>
</div>